### ISSUE TITLE
Can SSH be used now?

### ISSUE THREAD

**Issue by piaoxue925** [Dr238/SSH-Ramdisk-tool#13]
Can SSH be used now?

**Comment by Dr238** [comment]
I added the files for ssh but haven’t tested yet

**Comment by diyming** [comment]
How do this tool use ?? Do you want to program a software?

**Comment by Dr238** [comment]
Nah I just wanted to make sum stuff with my c++ "skillz". it is just for modifying your roots and doing some other stuff on iOS 14 and below (if it works)

**Comment by diyming** [comment]
Do you have a detailed tutorial?

**Comment by diyming** [comment]
How do you run it?

**Comment by Dr238** [comment]
./RamdiskMaker -d your identifier -i the iOS version of the Ramdisk -b the boardconfig (can be found on ipsw.me) -s the path to your device's shsh blob

**Comment by diyming** [comment]
Can you give an example of using the input code? identifier  What is it?

**Comment by cpablast** [comment]
> Can you give an example of using the input code? identifier What is it?

-d identifier
-i version
-b board
-s blob
-p pwn the device and remove sigchecks

-d iPhone8,2 -i 14.4.1 -b N66AP -s /Users/legacy/iPhone/ssh/5012397929000_iPhone8,2_n66ap_14.4.1-18D61_3a88b7c7502f2f0510abc432104a15ebd8bd7154.shsh2

**Comment by diyming** [comment]
Is there a detailed run code??

**Comment by cpablast** [comment]
There is no detailed run, the tool is still in development mode, you have to experiment with it and raise any issues you encounter.

**Comment by cpablast** [comment]
> Is this tool to open the iOS SSH channel? Do you have a detailed run? Thank you

There is no detailed run, the tool is still in development mode, you have to experiment with it and raise any issues you encounter.

**Comment by Dr238** [comment]
> > Is this tool to open the iOS SSH channel? Do you have a detailed run? Thank you
> 
> There is no detailed run, the tool is still in development mode, you have to experiment with it and raise any issues you encounter.

Exactly. Please try your devices and if it does not work open an issue and i will try my best to fix it.

**Comment by diyming** [comment]
-d iPhone8,2 -i 14.4.1 -b  What is the identity after this -b?

**Comment by diyming** [comment]
How to extract (-B) identifier

**Comment by Dr238** [comment]
-b is your boardconfig and can be found on ipsw.me. Just select your device and when you’re on the page for ipsw’s click on device information and underneath boardconfig is the parameter for the -b option. Just copy and paste that after the -b option

**Comment by diyming** [comment]
Still don't understand. Can you send a picture answer?

**Comment by cpablast** [comment]
> Still don't understand. Can you send a picture answer?
In the picture below you will find the 
-d identifier = identifier
-i version = IOS Version
-b board = BoardConfig

![info](https://user-images.githubusercontent.com/74069526/157671245-d1506a12-76aa-4ba9-87c8-437d2c16c541.jpg)

**Comment by diyming** [comment]
Thank you very much


---Original---
From: ***@***.***&gt;
Date: Thu, Mar 10, 2022 21:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] Can SSH be used now? (Issue #13)




  
Still don't understand. Can you send a picture answer?
 In the picture below you will find the
 -d identifier = identifier
 -i version = IOS Version
 -b board = BoardConfig
  

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by diyming** [comment]
Error: url required!




How can we fix this error?




---Original---
From: ***@***.***&gt;
Date: Fri, Mar 11, 2022 05:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] Can SSH be used now? (Issue #13)




 
Closed #13.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
