### ISSUE TITLE
1

### ISSUE THREAD

**Issue by diyming** [Dr238/SSH-Ramdisk-tool#16]
1

**Comment by diyming** [comment]
Run iBEC for the last project.... Have you not finished running the last few? ? The phone didn't run the code?

**Comment by diyming** [comment]
链接:https://pan.baidu.com/s/14yzxnFi8QifGGJ57dkgmJg 
提取码:kf4w

**Comment by diyming** [comment]
Above is the picture link

**Comment by cpablast** [comment]
Are you using a hackintosh or real mac?

**Comment by diyming** [comment]
Black Apple 10.15.7

**Comment by Dr238** [comment]
Send me the parameters you entered and i see you are using an old version of the tool clone the latest repo i made a few changes

**Comment by diyming** [comment]
ok

**Comment by diyming** [comment]
Is it running code input?  I use it according to your usage.  .  -d iPhone10,2 -i14.5.1-ba21ap -s bolb.shsh -p



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 12, 2022 22:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
Send me the parameters you entered and i see you are using an old version of the tool clone the latest repo i made a few changes
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by diyming** [comment]
Is it running code input?  I use it according to your usage.  .  -d iPhone10,2 -i14.5.1-ba21ap -s bolb.shsh -p

**Comment by cpablast** [comment]
i think -p is used separate

**Comment by diyming** [comment]
How do you enter codes?  ?



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 00:29 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
i think -p is used separate
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
for bolb.shsh did you enter you actual blob?

**Comment by cpablast** [comment]
What is your iphone model?

**Comment by diyming** [comment]
How to query 8p 3 net blob?  ?



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 00:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
for bolb.shsh did you enter you actual blob?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
https://shsh.host/

**Comment by Dr238** [comment]
The -p can be used apart from -d OR with -d

**Comment by diyming** [comment]
blob is the shsh2 file that the machine has now?  ?



---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 00:34 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
for bolb.shsh did you enter you actual blob?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dr238** [comment]
> blob is the shsh2 file that the machine has now? ?
Yes that is the .shsh2 file of your device. Ios version does not matter the blob just needs to be youre device's

**Comment by cpablast** [comment]
> Yes that is the .shsh2 file of your device. Ios version does not matter the blob just needs to be your device's

btw does the script auto gen the shsh blob or it has to be entered manually?

**Comment by Dr238** [comment]
No I'm not that advanced... you just have to drag and drop the shsh blob file you saved after the -s opt

**Comment by diyming** [comment]
链接:https://pan.baidu.com/s/1iutGu3zZDnnKVlU6ivNjjg 
提取码:q9ys

**Comment by diyming** [comment]
Why can't the run be finished?  ?

**Comment by diyming** [comment]
Can you give an example of this bolb?&nbsp; &nbsp; I directly add -s to shsh2 to get the path.&nbsp; .&nbsp; .&nbsp; The result is still the same.&nbsp; .&nbsp; .


---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 03:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
No I'm not that advanced... you just have to drag and drop the shsh blob file you saved after the -s opt
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by diyming** [comment]
Can you give an example of this bolb?&nbsp; &nbsp; I directly add -s to shsh2 to get the path.&nbsp; .&nbsp; .&nbsp; The result is still the same.&nbsp; .&nbsp; .


---Original---
From: ***@***.***&gt;
Date: Sun, Mar 13, 2022 01:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




  
Yes that is the .shsh2 file of your device. Ios version does not matter the blob just needs to be your device's
  
btw does the script auto gen the shsh blob or it has to be entered manually?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
@diyming  Connect your phone to 3utools and send me the ecid I will send you the blob for your phone

**Comment by diyming** [comment]
001365083853C02E

---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 00:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
@diyming  Connect your phone to 3utools and send me the ecid I will send you the blob for your phone
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
phone model?

**Comment by diyming** [comment]
8p  iPhone 10.2

**Comment by diyming** [comment]
8p&nbsp; &nbsp;iPhone 10.2



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 00:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
phone model?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
https://shsh.host/5459110536658990

**Comment by diyming** [comment]
thanks.  .  I'll try when

**Comment by diyming** [comment]
Is this the input code -d iPhone10, 2 -i 14.5.1 -DA21AP -s followed by this shsh2?  is not it?



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 00:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




 
https://shsh.host/5459110536658990
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cpablast** [comment]
> Is this the input code -d iPhone10, 2 -i 14.5.1 -DA21AP -s followed by this shsh2? is not it?
this is becoming a repetitive question 
-d iPhone10, 2 -i 14.5.1 -b DA21AP -s /Users/legacy/iPhone/ssh/5012397929000_iPhone8,2_n66ap_14.4.1-18D61_3a88b7c7502f2f0510abc432104a15ebd8bd7154.shsh2

**Comment by diyming** [comment]
thanks




---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 02:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] 1 (Issue #16)




  
Is this the input code -d iPhone10, 2 -i 14.5.1 -DA21AP -s followed by this shsh2? is not it?
 this is becoming a repetitive question
 -d iPhone10, 2 -i 14.5.1 -b DA21AP -s /Users/legacy/iPhone/ssh/5012397929000_iPhone8,2_n66ap_14.4.1-18D61_3a88b7c7502f2f0510abc432104a15ebd8bd7154.shsh2
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
