### ISSUE TITLE
Hello, how to solve this problem?

### ISSUE THREAD

**Issue by GudeSAT** [Dr238/SSH-Ramdisk-tool#2]
[i] Patched bootchain now only the ramdisk is left to customise
Wanna customise the ramdisk yourself or should i? type n to exit & y to proceed: y
**sh: ldid2: command not found**
/Volumes/SkyD19D52.arm64CustomerRamDisk/usr/local/bin/restored_external -> /Volumes/SkyD19D52.arm64CustomerRamDisk/usr/local/bin/restored_external_original
restored_external -> /Volumes/SkyD19D52.arm64CustomerRamDisk/usr/local/bin/restored_external

ldid2: command not found

**Comment by Dr238** [comment]
install ldid with:

brew install ldid

ldid2 will be installed with it this should fix it

**Comment by GudeSAT** [comment]
00:18:10 [8] stitching IM4M to trustcache..
rtsc
[e] cannot read 'IM4M'

thank you

**Comment by Dr238** [comment]
after -s option you specified the full path to your blob right?
And you're on catalina or higher i suppose

**Comment by GudeSAT** [comment]
yes

**Comment by GudeSAT** [comment]
Last login: Thu Mar  3 01:09:48 on ttys001
gude@192 ~ % ssh root@localhost -p 2222
kex_exchange_identification: read: Connection reset by peer
gude@192 ~ % 

can't open ssh.    How to fix it ? Please tell me , thank you

**Comment by Dr238** [comment]
As i mentioned in the readme. I'm still working on the ssh part so you gotta wait for a bit till i finish that.

**Comment by GudeSAT** [comment]
Thank you for answering my question. This is a good project.

**Comment by Dr238** [comment]
Thank you

**Comment by 473407005** [comment]
how to solve this error?thanks!
![Uploading A96E5ED4-2EF0-4711-AEAE-3A9C488781E7.jpeg…]()
