### ISSUE TITLE
Hello author.  .  

### ISSUE THREAD

**Issue by diyming** [Dr238/SSH-Ramdisk-tool#20]
Hello author.  .  Now the SSH tools are researched there.  When can I use SSH to connect to the device

**Comment by diyming** [comment]
How is the development progress now?  ?

**Comment by Dr238** [comment]
I am still working on the ssh part but in the meantime fixing the code

**Comment by frankl1m** [comment]
Where can check the ssh dependecies for debug?

**Comment by Dr238** [comment]
I just added dropbear and openssl debs no ssh files

**Comment by diyming** [comment]
No ... I haven't played ... I'm following you !!!!



---Original---
From: ***@***.***&gt;
Date: Sat, Mar 19, 2022 19:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] Hello author.  .   (Issue #20)




 
Where can check the ssh dependecies for debug?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by diyming** [comment]
Why is this error always reported?  ?  ?  The ports have been changed.  .  .  same problem

---Original---
From: ***@***.***&gt;
Date: Sat, Mar 19, 2022 21:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Dr238/SSH-Ramdisk-tool] Hello author.  .   (Issue #20)




 
I just added dropbear and openssl debs no ssh files
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
