### ISSUE TITLE
url error

### ISSUE THREAD

**Issue by Ic3ly** [Dr238/SSH-Ramdisk-tool#21]
<img width="570" alt="Screen Shot 2022-03-19 at 08 58 17" src="https://user-images.githubusercontent.com/101820800/159103443-9efe0e42-c5e1-4286-bcf8-b0fc7c39e4e1.png">

any help for this issue ?
using mac pro with 12.1 os

**Comment by Dr238** [comment]
What were your parameters?

**Comment by Ic3ly** [comment]
> What were your parameters?

./RamdiskMaker -d iPhone 10, 4 -i 15.1 -b D201AP -s bla/blob.shsh2

Sometimes showing connection issue
Like this : 

![image](https://user-images.githubusercontent.com/101820800/159124025-5ea11805-540e-4606-9c58-f722618e3850.jpeg)

**Comment by Dr238** [comment]
iPhone10,4 not with the space between iPhone and 10,4

**Comment by Dr238** [comment]
And after the -s opt you dragged and dropped your shsh blob file right

**Comment by Ic3ly** [comment]
Solved thanks
