### ISSUE TITLE
USB restricted

### ISSUE THREAD

**Issue by frankl1m** [Dr238/SSH-Ramdisk-tool#22]
I was checked your script, with some min patch it should work on ios 14, the problem is that need before patch the USB restricted first i was checking that iproxy detect as a generic udid that changes every time and deny any relay, you have any idea how to fix it?

**Comment by frankl1m** [comment]
there is 2 plists on User Configuration profiles that i patched dont work either i think that need others services load, dont founded yet

**Comment by Dr238** [comment]
Alright thanks for the info I’m on it

**Comment by cpablast** [comment]
To patch usb you need to run several commands after changing the plist, otherwise the device will just go back to restriction mode

**Comment by Dr238** [comment]
> To patch usb you need to run several commands after changing the plist, otherwise the device will just go back to restriction mode

I did not know that.. could you maybe help me?
If you want to help me add me on discord (if you have)
Dr238

**Comment by frankl1m** [comment]
> To patch usb you need to run several commands after changing the plist, otherwise the device will just go back to restriction mode

Yes is correct, i am debugging not success yet

**Comment by frankl1m** [comment]
> > To patch usb you need to run several commands after changing the plist, otherwise the device will just go back to restriction mode
> 
> I did not know that.. could you maybe help me? If you want to help me add me on discord (if you have) Dr238

I have and ask, bcz now i finally get a device without passcode, but AES keys for ios 15.4 are not avaliable yet for some models, you successfully tested any device that allow SSH, i mean without passcode

**Comment by Dr238** [comment]
> > > To patch usb you need to run several commands after changing the plist, otherwise the device will just go back to restriction mode
> > 
> > 
> > I did not know that.. could you maybe help me? If you want to help me add me on discord (if you have) Dr238
> 
> I have and ask, bcz now i finally get a device without passcode, but AES keys for ios 15.4 are not avaliable yet for some models, you successfully tested any device that allow SSH, i mean without passcode?

what do you mean? you can get them with ipwndfu or a am I wrong

**Comment by cpablast** [comment]
you need to patching the plist files, you need to run chflags uchg so that the files can't be changed by the system. This is will make the usb restriction off

**Comment by Dr238** [comment]
I understand the chflags but which plist files specifically? bc I just loaded the "USBDeviceConfiguration.plist" and that turned on USB Restricted Mode I guess

**Comment by cpablast** [comment]
you need to turn off restriction in this files.. I will delete the names later
PublicEffectiveUserSettings.plist
EffectiveUserSettings.plist

**Comment by Dr238** [comment]
And where are they located in the ramdisk? I cannot find them

**Comment by frankl1m** [comment]
@Dr238  Files that @cpablast  he mentions are not on ramdisk, is on local file system, i was trying to replacing from other device not success and set chflags uchg after but it dont work it brings to usb restricted mode or never allow usb. This together with substrate should be before restore external or after restore external command @cpablast ?

**Comment by frankl1m** [comment]
> > @Dr238 Files that @cpablast he mentions are not on ramdisk, is on local file system, i was trying to replacing from other device not success and set chflags uchg after but it dont work it brings to usb restricted mode or never allow usb. This together with substrate should be before restore external or after restore external command @cpablast ? before restore external i dont have usb connection at all
> 
> Ah alright. But add me on discord you both so we can talk there

Discord user?

**Comment by Dr238** [comment]
> > > @Dr238 Files that @cpablast he mentions are not on ramdisk, is on local file system, i was trying to replacing from other device not success and set chflags uchg after but it dont work it brings to usb restricted mode or never allow usb. This together with substrate should be before restore external or after restore external command @cpablast ? before restore external i dont have usb connection at all
> > 
> > 
> > Ah alright. But add me on discord you both so we can talk there
> 
> Discord user?

Dr238#1677

**Comment by cpablast** [comment]
I don't use discord

**Comment by frankl1m** [comment]
> Got reddit? If you do my username is Dr238

write you on discord

**Comment by D0lcegabbana** [comment]
Hi.  If iPhone without passcode.  You can run ramsisk and open ssh?
