### ISSUE TITLE
Dr238

### ISSUE THREAD

**Issue by 473407005** [Dr238/SSH-Ramdisk-tool#3]
How to solve this error ？please tell me that,thanks.
![383B3365-50E6-4004-BAD4-197879B7F37E](https://user-images.githubusercontent.com/72241403/156501534-b773972e-29ab-4e70-ba72-7f101c0b232d.jpeg)

**Comment by 473407005** [comment]
What about this?
![image](https://user-images.githubusercontent.com/72241403/156690416-9638a173-7a14-446f-ae63-cdaa230a603d.jpg)

**Comment by Dr238** [comment]
Did you put the device in pwned dfu and removed sig checks??

**Comment by piaoxue925** [comment]
How to remove sig checks,I also encountered the above problem.

**Comment by piaoxue925** [comment]
How to remove sig checks,I also encountered the above problem.ramdisk 0.6%

**Comment by piaoxue925** [comment]
<img width="544" alt="1b00ba0071ba230610c5d87d7dd3f7b" src="https://user-images.githubusercontent.com/101029593/156908780-ad52c3b1-ee77-4aeb-9b62-e8f2c5e80631.png">
