### ISSUE TITLE
A9The device cannot boot into ramdisk.

### ISSUE THREAD

**Issue by GudeSAT** [Dr238/SSH-Ramdisk-tool#4]
I can't access the boot interface with 6s, and my phone is on a black screen! How to solve it! I successfully entered ramdisk with iPhone8. Please tell me, thank you.

**Comment by Dr238** [comment]
Someone else had the same issue as you have right now.. i also have an 8 i tested on works fine but it seems that A8 and A9 are the problem. try this tool. it automatically removes sigchecks so you should be booting i hope...
https://github.com/dora2-iOS/ipwnder_lite.git

**Comment by GudeSAT** [comment]
It has been removed, but it still doesn't work.The computer display device is in recovery mode, but the mobile phone has a black screen. I come from China, and my English is not very good. Thank you for your patient answer. What is your email? Give you a document related to your project, which may help you fix these problems more quickly!
