### ISSUE TITLE
help me.man  mac 10.15.7

### ISSUE THREAD

**Issue by badboyhhhh** [Dr238/SSH-Ramdisk-tool#6]
![E44ACB4D-5ED2-4779-A1E7-D7197B4EF736](https://user-images.githubusercontent.com/100673673/156874438-e0d2c196-cbfe-4344-99fa-31c96f3554b4.jpeg)

**Comment by Dr238** [comment]
Hmn you are the 3rd person with this issue and i guess for you it is the same. Keys.html does not exist am i right? I will do a clean install of macos catalina myself and try to fix your problem.

**Comment by Dr238** [comment]
I found your error. c++ is case sensitive so that is why you could not get keys.html. after the "-d" option specify iPhone with uppercase P not lowercase. that was your error

**Comment by badboyhhhh** [comment]
# add dropbear resources
mkdir -p /Users/baba/Desktop/rd_skel/System/Library/LaunchDaemons/
mkdir -p /Users/baba/Desktop/rd_skel/etc/dropbear/
mv -v /Users/baba/Desktop/rd_skel/dropbear.plist /Users/baba/Desktop/rd_skel/System/Library/LaunchDaemons/dropbear.plist
mv -v /Users/baba/Desktop/rd_skel/id_rsa /Users/baba/Desktop/rd_skel/etc/dropbear/id_rsa
mv -v /Users/baba/Desktop/rd_skel/motd /Users/baba/Desktop/rd_skel/etc/motd
this is build ssh use dropbear. but i don*t dnow &nbsp;dropbear.plust id_rsa and motd how to get it.haha




发自我的iPhone


------------------ Original ------------------
From: Dr238 ***@***.***&gt;
Date: Sun,Mar 6,2022 9:27 PM
To: Dr238/SSH-Ramdisk-tool ***@***.***&gt;
Cc: badboyhhhh ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [Dr238/SSH-Ramdisk-tool] help me.man  mac 10.15.7 (Issue #6)





 
I found your error. c++ is case sensitive so that is why you could not get keys.html. after the "-d" option specify iPhone with uppercase P not lowercase. that was your error
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
