### ISSUE TITLE
unable to connect to device

### ISSUE THREAD

**Issue by piaoxue925** [Dr238/SSH-Ramdisk-tool#7]
<img width="550" alt="c1453d0295eebaba34f0b31424a098c" src="https://user-images.githubusercontent.com/101029593/156912752-657e1d42-24da-48ac-b1dd-007be944f736.png">
<img width="523" alt="b35a84b458fbdb010435a9e9fa1ad11" src="https://user-images.githubusercontent.com/101029593/156912755-d4f7c6cc-25cf-44ec-a2db-d51d959c056d.png">

**Comment by Dr238** [comment]
there is nothing wrong and as I mentioned in the readme I am working on the ssh part. So that is normal
