### ISSUE TITLE
ou.budy..help..

### ISSUE THREAD

**Issue by badboyhhhh** [Dr238/SSH-Ramdisk-tool#9]
![355B5B4A-E360-4743-88F3-B10D081855C6](https://user-images.githubusercontent.com/100673673/157005122-bac6abcd-76b2-4eee-981a-750cb7a6436a.jpeg)
thanks.

**Comment by piaoxue925** [comment]
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer/

**Comment by badboyhhhh** [comment]
thanks. i will try it ^-^
